# Create an OpenGL view:
/vis/open OGL 600x600-0+0

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors

# Draw geometry:
/vis/drawVolume

# Axes
/vis/scene/add/axes -1 0 0 0.5 m

# Specify view angle:
/vis/viewer/set/viewpointVector -1 1 -1
/vis/viewer/set/lightsVector -1 0 0

# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style surface
#/vis/viewer/set/auxilia/vis/scene/add/text2D 0 0 20 -1 -1 testryEdge true
/vis/viewer/set/lineSegmentsPerCircle 30

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set nu_e white
/vis/modeling/trajectories/drawByParticleID-0/set anti_nu_e white
/vis/modeling/trajectories/drawByParticleID-0/set geantino white
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set alpha yellow
/vis/modeling/trajectories/drawByParticleID-0/set GenericIon grey
/vis/modeling/trajectories/drawByParticleID-0/set neutron pink

# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate

# Set a title
# /vis/set/textColour 0.722 0.451 0.2 1
# /vis/scene/add/text2D -0.85 0.8 30 0 0 IPM in ESS LWU
# /vis/scene/add/date

# To get nice view
/vis/geometry/set/visibility World 0 true
/vis/geometry/set/colour WorldL 0 1 1 1 0.3
/vis/geometry/set/colour SRFL 0 1 1 0 0.2
/vis/geometry/set/colour tubOuterL 0 0.0 0.0 1 0.2
/vis/geometry/set/colour tubInnerL 0 0.0 1 1 0.2


# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

# For file-based drivers, use this to create an empty detector view:
/vis/viewer/flush